---
- name: restart vllm
  ansible.builtin.systemd:
    name: vllm
    state: restarted
    daemon_reload: true

- name: restart vllm-sanitizer
  ansible.builtin.systemd:
    name: vllm-sanitizer
    state: restarted
    daemon_reload: true
